// Writes docs/conformance.md from the run, and pins the number of claims.
//
// Two jobs, and the second is the one worth explaining. §9.1 of the plan is a
// hand-maintained prose account of what the UI check covers, and it had drifted
// in five places by the time anyone looked. A table generated by the run cannot
// drift: if a claim is not tested, it is not in the table.
//
// The pin replaces `EXPECTED_CHECKS` from the script this suite came from.
// Eleven of that script's checks sat inside `if` guards, so a run where a guard
// did not fire printed "22/22 passed" and looked green -- a smaller denominator
// reported as success. `test.fixme` avoids that by construction, since Playwright
// counts a fixme separately from a pass, but a test that stops being collected at
// all is still invisible. Hence the count.

import { writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import type {
  FullConfig,
  FullResult,
  Reporter,
  Suite,
  TestCase,
  TestResult,
} from "@playwright/test/reporter";

/**
 * Every claim this suite makes, counted. Raise it when adding a test; a drop is
 * a failure, because a claim that stopped being collected proved nothing and
 * said nothing.
 *
 * **The failure this pin raises does not mark any test as failed.** It comes out
 * of `onEnd` as a reporter-level status, so a run that adds a claim and forgets
 * this number still prints "N passed, 0 failed" above the refusal. Five claims
 * were added over 2026-09-16 without raising it, and three completion reports
 * read the pass counts and called the suite green while the run was exiting 1.
 * If you are checking whether the suite passes, check the exit code.
 */
const EXPECTED_TESTS = 210;


type Status = "built" | "broken" | "not-built" | "unobserved";

interface Row {
  claim: string;
  source: string;
  status: Status;
  detail: string;
}

/** `"a claim [SOURCE §section]"` -> claim and source, kept separate columns. */
function split(title: string): { claim: string; source: string } {
  const match = /^(.*)\s+\[([^\]]+)\]$/.exec(title);
  return match
    ? { claim: match[1], source: match[2] }
    : { claim: title, source: "—" };
}

const MARK: Record<Status, string> = {
  built: "✅ built",
  broken: "❌ broken",
  "not-built": "🚧 not built",
  unobserved: "⚪ not observed",
};

export default class ConformanceReporter implements Reporter {
  private readonly rows = new Map<string, Row[]>();
  private root!: Suite;
  private rootDir = "";
  // `__dirname`, not `import.meta.url`: Playwright transpiles reporters to CJS.
  // `config.rootDir` would be `ide/tests`, since Playwright roots the config at
  // `testDir` -- so the output path is relative to this file instead.
  private readonly out = join(__dirname, "../../../docs/conformance.md");

  onBegin(config: FullConfig, suite: Suite): void {
    this.root = suite;
    this.rootDir = config.rootDir;
  }

  onTestEnd(test: TestCase, result: TestResult): void {
    // Only `conformance/` is a claim about a document. `tests/regression.spec.ts`
    // holds checks worth keeping that no document makes -- an edge must have an
    // arrowhead -- and listing them here would inflate the table with rows that
    // trace to nothing.
    if (!test.location.file.includes("/conformance/")) return;

    const isFixme = test.annotations.some((a) => a.type === "fixme");
    const skipReason = test.annotations.find((a) => a.type === "skip")?.description;

    let status: Status;
    let detail = "";
    if (isFixme) {
      status = "not-built";
      detail = test.annotations.find((a) => a.type === "fixme")?.description ?? "";
    } else if (result.status === "skipped") {
      // Deliberately distinct from "not built": the feature may well exist, but
      // this run could not get into a state where the claim was observable. A
      // staged-loading window that closed between two samples is the case that
      // matters, and calling it a pass would be a lie.
      status = "unobserved";
      detail = skipReason ?? result.error?.message ?? "the run could not observe it";
    } else if (result.status === "passed") {
      status = "built";
    } else {
      status = "broken";
      detail = (result.error?.message ?? "").split("\n")[0];
    }

    const file = relative(this.rootDir, test.location.file);
    const list = this.rows.get(file) ?? [];
    const { claim, source } = split(test.title);
    list.push({ claim, source, status, detail });
    this.rows.set(file, list);
  }

  onEnd(result: FullResult): { status?: FullResult["status"] } {
    const total = this.root
      .allTests()
      .filter((t) => t.location.file.includes("/conformance/")).length;
    const all = [...this.rows.values()].flat();
    const count = (s: Status) => all.filter((r) => r.status === s).length;

    const lines: string[] = [
      "<!-- Generated by `npx playwright test` in ide/. Do not edit by hand. -->",
      "",
      "# Conformance: what the documents claim, and what the application does",
      "",
      "Each row is one claim from a design document, checked against a running",
      "Gearbox Studio. A 🚧 row is a `test.fixme` -- the test is written and named,",
      "the feature is not there yet. A ⚪ row is a claim this run could not put",
      "itself in a position to observe, which is reported rather than counted as a",
      "pass.",
      "",
      `Claims: **${all.length}** — ${count("built")} built, ${count("not-built")} not built, ` +
        `${count("broken")} broken, ${count("unobserved")} not observed.`,
      "",
      "Only browser-observable claims appear here. Engine-side claims are tested in",
      "Rust, and the ADRs' own Confirmation sections say which.",
      "",
    ];

    for (const [file, rows] of [...this.rows.entries()].sort()) {
      lines.push(`## \`${file}\``, "", "| Claim | Source | Status | Note |", "|---|---|---|---|");
      for (const row of rows) {
        const note = row.detail.replace(/\|/g, "\\|").slice(0, 140);
        lines.push(`| ${row.claim} | \`${row.source}\` | ${MARK[row.status]} | ${note} |`);
      }
      lines.push("");
    }

    if (all.length === 0) {
      // A run that collected nothing must not overwrite the record of a run that
      // collected something. This happened: a `globalSetup` failure produced a
      // table reading "Claims: 0", replacing 86 rows of real state with an empty
      // shell. An empty table is not a finding, it is the absence of a run.
      process.stdout.write(
        `\nno claims collected, so ${this.out} was left as it was. ` +
          `Something failed before the tests were reached -- look above this line.\n`,
      );
      return { status: "failed" };
    }

    writeFileSync(this.out, lines.join("\n"));
    process.stdout.write(`\nconformance table: ${this.out}\n`);

    if (total !== EXPECTED_TESTS) {
      process.stdout.write(
        `\nFAIL collected ${total} claims, expected ${EXPECTED_TESTS}. ` +
          `A claim that stops being collected proves nothing and reports nothing, ` +
          `so this is a failure. Update EXPECTED_TESTS when adding one.\n`,
      );
      return { status: "failed" };
    }
    return { status: result.status };
  }
}
